# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4305edef2bb36a8ea883c05189c2a8950eb53723746fd98e06a759da84b7d7607701654720468d746e37cde3f1c9ce8307080f8d632215b61811ea97e6d5bc9

test:
  secret_key_base: 4b5480c2263e0871d30a161b6af969a2fd394ff4a9ecb95420d5641171ff20a570da7352d5ad01e241c9d6d582817f877da0d7da29413b9d11a78b34be39410b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
